---
# https://github.com/prometheus-operator/prometheus-operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sql-mysqlsql
  namespace: db
  labels:
    prometheus: devops
spec:
  endpoints:
  - port: metrics
    interval: 60s
    scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
    - db
  selector:
    matchLabels:
      app.kubernetes.io/instance: mysql	
